services:
  backend-dev:
      build:
        context: ../backend
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
        - "0.0.0.0:8082:8080"
      env_file:
        - .env
  frontend-dev:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
        - NEXT_PUBLIC_MINIO_URL=${NEXT_PUBLIC_MINIO_URL}
        - NEXT_PUBLIC_MINIO_BUCKET=${NEXT_PUBLIC_MINIO_BUCKET}
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - NEXT_PUBLIC_MINIO_URL=${NEXT_PUBLIC_MINIO_URL}
      - NEXT_PUBLIC_MINIO_BUCKET=${NEXT_PUBLIC_MINIO_BUCKET}
volumes:
  n8n_data:
    external: true