services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.17.3
    restart: always
    ports:
      - "0.0.0.0:5678:5678"
    env_file:
      - .env
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_SECURE_COOKIE=false
      - N8N_PORT=5678
      # - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      # - NODE_ENV=production
      # - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      # - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      # - TZ=${GENERIC_TIMEZONE}
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        - APP_VERSION=${BACKEND_VERSION}
    restart: unless-stopped
    ports:
      - "0.0.0.0:8081:8080"
    env_file:
      - .env
  
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
        - NEXT_PUBLIC_MINIO_URL=${NEXT_PUBLIC_MINIO_URL}
        - NEXT_PUBLIC_MINIO_BUCKET=${NEXT_PUBLIC_MINIO_BUCKET}
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - NEXT_PUBLIC_MINIO_URL=${NEXT_PUBLIC_MINIO_URL}
      - NEXT_PUBLIC_MINIO_BUCKET=${NEXT_PUBLIC_MINIO_BUCKET}

volumes:
  n8n_data:
    external: true