services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "0.0.0.0:5678:5678"
    env_file:
      - .env
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_SECURE_COOKIE=false
      - N8N_PORT=5678
      # - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      # - NODE_ENV=production
      # - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      # - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      # - TZ=${GENERIC_TIMEZONE}
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

  backend:
    build:
      context: ../backend-legacy
      dockerfile: Dockerfile
    restart: always
    ports:
      - "0.0.0.0:8080:8080"
    env_file:
      - .env
    environment:
      - ConnectionStrings__Postgres=Host=${DB_POSTGRESDB_HOST};Port=${DB_POSTGRESDB_PORT};Database=${DB_WAREHOUSE_DATABASE};Username=${DB_WAREHOUSE_USER};Password=${DB_WAREHOUSE_PASSWORD}

volumes:
  n8n_data:
    external: true