[minio]
type = s3
provider = Minio
env_auth = true
access_key_id = dCmMZDmcqHNrJmaoPrss
secret_access_key = 3wJcrUTetV3l8W6JSAh75PG7BpyQysTQzyzjdksw
endpoint = http://192.168.1.191:9000
acl = private

