@echo off

:: --- CONFIGURATION (generated by installer — edit LOCAL_VIDEO_FOLDER and MINIO_BUCKET only) ---
set LOCAL_VIDEO_FOLDER=%USERPROFILE%\Videos\Warehouse
set MINIO_BUCKET=packing-korat
set RCLONE_CONFIG=%~dp0rclone.conf
set RCLONE_EXE=%~dp0rclone.exe

for /f "tokens=2" %%D in ("%date%") do set DATE_CLEAN=%%D
set DATE_CLEAN=%DATE_CLEAN:/=-%

set LOG_DIR=%~dp0logs\sync
set LOG_FILE=%LOG_DIR%\%COMPUTERNAME%_%DATE_CLEAN%.log

echo Starting MinIO sync for %COMPUTERNAME% at [%date% %time%]...
echo From folder: %LOCAL_VIDEO_FOLDER% to bucket: %MINIO_BUCKET%/%COMPUTERNAME%/

if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"

echo [%date% %time%] Starting upload for %COMPUTERNAME% >> "%LOG_FILE%"

"%RCLONE_EXE%" copy "%LOCAL_VIDEO_FOLDER%" minio:%MINIO_BUCKET%/%COMPUTERNAME%/ ^
  --config "%RCLONE_CONFIG%" ^
  --min-age 1h ^
  --transfers 4 ^
  --checkers 8 ^
  --log-file "%LOG_FILE%" ^
  --log-level INFO ^
  --stats 30s ^
  --progress ^
  2>&1

if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] rclone failed with exit code %ERRORLEVEL%
    echo [%date% %time%] [ERROR] Upload failed with exit code %ERRORLEVEL% >> "%LOG_FILE%"
) else (
    echo [OK] Upload complete.
    echo [%date% %time%] Upload complete >> "%LOG_FILE%"
)